[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "https://www.alkalakehotel.co.in/:splat"
  status = 301
  force = true

[build.environment]
  NODE_VERSION = "18"
